# Conda environment file used to run the notebooks
name: pavics-sdi
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.10,<3.13
  - birdy
  - cartopy
  - cf_xarray >=0.10.4
  - clisops >=0.16.1
  - dask >=2024.8.1
  - fiona
  - geopandas >=1.0
  - geoviews
  - hvplot
  - intake-esm
  - ipyleaflet
  - ipython
  - matplotlib
  - netcdf4
  - numba >=0.58.0
  - numpy >=1.25.0

  - psutil
  - pydap
  - pykdtree  # Fixes cartopy bug arising with scipy 1.11
  - rasterio
  - rioxarray
  - siphon
  - shapely >=2.0
  - xarray >=2023.11.0
  - xclim >=0.57.0
  - xesmf !=0.8.8
  - xscen >=0.12.1
  - xsdba >=0.4.0
  - pip:
      - prometheus_api_client >0.5.5
      - prometheus-pandas
